enum APP_ERRORS {
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_CREATED_FAILED = 'TRANSACTION_CREATED_FAILED',
  INSUFFICIENTS_FUNDS = 'INSUFFICIENTS_FUNDS',
}

export default APP_ERRORS;
